void vardoIvedimas(Stud &laik);
void pazymiuIvedimas(Stud &laik);
void vardoGeneravimas(Stud &laik);
void pazymiuGeneravimas(Stud &laik);
bool pagalVarda(Stud &a, Stud &b);
bool pagalPavarde(Stud &a, Stud &b);
bool pagalVidurki(Stud &a, Stud &b);
bool pagalMediana(Stud &a, Stud &b);
void testas(string failoPavadinimas);
int rusiavimoPasirinkimas();
string failoPasirinkimas(string klausimas);
void failoGeneravimas(int failoIlgis);
int galutinioBaloPasirinkimas();
double vidurkis(vector <int> nd);
double mediana(vector <int> nd);