void vardoIvedimas(Stud &laik);
void pazymiuIvedimas(Stud &laik);
void vardoGeneravimas(Stud &laik);
void pazymiuGeneravimas(Stud &laik);
void ivedimas(vector<Stud> &studentai, int &meniuPasirinkimas);
double vidurkis(vector<int> nd);
double mediana(vector<int> nd);
void nuskaitymasSuBuferiu(vector<Stud> &studentai, string failoPavadinimas);
void isvedimas(vector<Stud> studentai, int galutinioBaloPasirinkimas, ostream & isvedimoBudas);
bool pagalVarda(Stud &a, Stud &b);
bool pagalPavarde(Stud &a, Stud &b);
bool pagalVidurki(Stud &a, Stud &b);
bool pagalMediana(Stud &a, Stud &b);
void testas(string failoPavadinimas);
int rusiavimoPasirinkimas();
void rusiavimas(vector<Stud> &studentai, int pasirinkimas);
string failoPasirinkimas(string klausimas);
void failoGeneravimas(int failoIlgis, string & sugeneruotasFailas);
int galutinioBaloPasirinkimas();
void isskaidymasIGrupes(vector <Stud> studentai, vector <Stud> & protingi, vector <Stud> & neprotingi, int galutinisBalas);
void tyrimas(vector <Stud> studentai);